### ISSUE TITLE
Instruction to set background image

### ISSUE THREAD

**Issue by alexvong243f** [ahungry/color-theme-ahungry#2]
Hi,
I notice some of the screenshots contain a background image. How do you manage to do it? Could you please put it in the README?

**Comment by ahungry** [comment]
Unfortunately the theme itself can't set a background image, however if you want to accomplish it, what I do (and used in those screenshots) is to:
- Use a terminal (urxvt in my case, but any that can set a background image or transparency will work)
- Run emacs in tty mode (launch emacs with `emacs -nw` instead of plain old `emacs` command)
- Load the theme (it will not overwrite the transparent background with a colored one like most the other themes do)
- Enjoy a theme that works well with transarency + background

**Comment by alexvong243f** [comment]
Thanks for the info, I though there would be a emacs mode for it :)

**Comment by ahungry** [comment]
I looked into it before a few years ago, and the best I could find for GUI emacs was applying a custom patch and compiling it yourself (unfortunately at the time I couldn't get it to work even with the custom patch applied)
